package com.dv1431_chatapp

import android.support.v7.app.AppCompatActivity
import android.os.Bundle
import android.widget.ListView
import com.dv1431_chatapp.database.ChatGroup
import com.dv1431_chatapp.database.User
import com.google.firebase.database.FirebaseDatabase
import kotlinx.android.synthetic.main.activity_create_group.*

class CreateGroupActivity : AppCompatActivity() {

    private var mGroupListView: ListView? = null
    private var mGroupAdapter: UserListAdapter? = null
    private lateinit var mUserList: ArrayList<String>
    private lateinit var mUsers: ArrayList<User>

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_create_group)
        initiateGUIComponents()
        mUsers = ArrayList()
    }

    // conny tar en edtxt string, skickar upp o kollar om den finns, och då lägger han den i mUserList, sedan skapar ni grp med
    //grp name och alla users i listen, för dom är guaranteed finnas

    private fun addUser() {
        val user = User("id1", "test@test.test", "testuser")
        mUsers.add(user)
        // TODO: Check if user exist and use the ADD below, Else write a "Toast"
        mGroupAdapter!!.add(user.getEmail())
    }

    private fun initiateGUIComponents(){
        mUserList = ArrayList<String>()
        mGroupListView = createGroupActivity_usersInGroup_listView
        mGroupAdapter = UserListAdapter(this, createGroupActivity_usersInGroup_listView.id, mUserList)
        mGroupListView!!.adapter = mGroupAdapter
        createGroupActivity_addUser_btn.setOnClickListener{
            addUser()
        }
        createGroupActivity_createGrp_btn.setOnClickListener {
            createGroup()
        }
    }

    private fun createGroup() {
        val group = ChatGroup()
        group.setName(createGroupActivity_grpName_edtxt.text.toString())
        group.setUsers(mUsers)

        // Generate a unique reference as group id
        val groupsRef = FirebaseDatabase.getInstance().getReference("groups")
        val newGroupRef = groupsRef.push()

        println("parent: " + newGroupRef.parent + ", childkey: " + newGroupRef.key)
        // Add group to the generated group id
        newGroupRef.setValue(group)

        // Get the unique ID generated by push()
        val groupId = newGroupRef.key

        group.setId(groupId)
    }

}